#!/bin/bash
#
# Virtuoso			Bulk Loader Script
#
# Description: Bulk loader script for Virtuoso
# Usage: vload [virtuososo_allowed_directory] [data_file] [graph_uri] [log_directory] [virtuoso_password]

# Get input arguments
args=("$@")
if [ $# -ne 5 ]; then
    echo "Wrong number of arguments. Correct usage: \"vload [virtuososo_allowed_directory] [data_file] [graph_uri] [log_directory] [virtuoso_password]\""
else
    VAD=${args[0]}
    data_file=${args[1]}
    graph_uri=${args[2]}
    LOG_DIR=${args[3]}
    VIRT_PSWD=${args[4]}

    LOG_DATA_FILE=`echo $data_file | sed 's/[^a-zA-Z0-9\.\-\_]/-/g'`
    LOG_GRAPH_URI=`echo $graph_uri | sed 's/[^a-zA-Z0-9i\.\-\_]/-/g'`
    LOGFILE="$LOG_DIR/vload_${LOG_DATA_FILE}_${LOG_GRAPH_URI}-`date +%Y%m%d-%H%M%S`.log"
    # Status message
    echo "Loading triples into graph <$graph_uri>..."

    # Log into Virtuoso isql env
    isql_cmd="isql-v -U dba -P $VIRT_PSWD"

    # Build the Virtuoso commands
    load_func="ld_dir('$VAD', '$data_file', '$graph_uri');"
    run_func="rdf_loader_run();"
    select_func="select * from DB.DBA.load_list;"
   
    # Run the Virtuoso commands
    ${isql_cmd} << EOF &> ${LOGFILE}
	    $load_func
            $run_func
            $select_func   
            exit;
EOF

    # Write the load commands to the log 
    echo "----------" >> ${LOGFILE}
    echo $load_func >> ${LOGFILE}
    echo $run_func >> ${LOGFILE}
    echo ${select_func} >> ${LOGFILE}
    echo "----------" >> ${LOGFILE}

    result=$?

    if [ $result != 0 ]
    then
        "Failed to load! Check ${LOGFILE} for details."
        exit 1
    fi

    # Status message
    echo "Loading finished! Check ${LOGFILE} for details."	
    exit 0
fi

